name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.13'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: python3 -m pip install pytest

    - name: Install
      run: python3 -m pip install -q .

    - name: Test
      run: python3 -m pytest -v
